# Default values for twig2.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1
image:
  repository: builditdigital/twig2
  tag: latest
  pullPolicy: Always
service:
  name: twig2
  type: ClusterIP
  externalPort: 80
  internalPort: 80
  hostName:
  #Heimdall service url (internal call is made by edge proxy)
  #authUrl:
resources:
  limits:
    cpu: 50m
    memory: 64Mi
  requests:
    cpu: 30m
    memory: 32Mi
app:
  noauth: true
