# Build specification for building project under Amazon CodeBuild

version: 0.1
#environment_variables:
#  plaintext:
phases:
  pre_build:
    commands:
      - echo -n "$CODEBUILD_BUILD_ID" | sed "s/.*:\([[:xdigit:]]\{7\}\).*/\1/" > /tmp/build_id.out
      - printf "%s:%s" "$REPOSITORY_URI" "$(cat /tmp/build_id.out)" > /tmp/build_tag.out
      - printf '{"tag":"%s"}' "$(cat /tmp/build_id.out)" > /tmp/build.json
      - cat /tmp/build_id.out
      - cat /tmp/build_tag.out
      - cat /tmp/build.json
      - $(aws ecr get-login)
      - apt-get install nodejs
      - apt-get install npm
      - ln -s /usr/bin/nodejs /usr/bin/node
  build:
    commands:
      - npm install
      - CHROME_BIN=/usr/bin/google-chrome xvfb-run -s '-screen 0 1280x1024x16' npm run test:ci
      - npm run lint
      - npm run build:prod
      - docker build --tag "$(cat /tmp/build_tag.out)" .
  post_build:
    commands:
      - docker push "$(cat /tmp/build_tag.out)"
artifacts:
  files: /tmp/build.json
  discard-paths: yes
