# Build specification for building project under Amazon CodeBuild

version: 0.1
#environment_variables:
#  plaintext:
phases:
  install:
    commands:
      - apt-get update
      - apt-get -y install curl
      - curl -sL https://deb.nodesource.com/setup_8.x | sudo -E bash -
      - sudo apt-get install -y nodejs
      - npm --version
      - node --version
      - docker --version
  pre_build:
    commands:
      - echo -n "$CODEBUILD_BUILD_ID" | sed "s/.*:\([[:xdigit:]]\{7\}\).*/\1/" > /tmp/build_id.out
      - printf "%s:%s" "$REPOSITORY_URI" "$(cat /tmp/build_id.out)" > /tmp/build_tag.out
      - printf '{"tag":"%s"}' "$(cat /tmp/build_id.out)" > /tmp/build.json
      - cat /tmp/build_id.out
      - cat /tmp/build_tag.out
      - cat /tmp/build.json
      - $(aws ecr get-login)
  build:
    commands:
      - docker run --rm -v "$PWD":/app trion/ng-cli-e2e /bin/bash -c "npm install && npm run test:e2e:ci -- --base-href $ENDPOINT_URI"
