# Build specification for building project under Amazon CodeBuild

version: 0.1
#environment_variables:
#  plaintext:
phases:
  install:
    commands:
      - apt-get update
      - apt-get -y install curl
#      - curl -sL https://deb.nodesource.com/setup_6.x -o nodesource_setup.sh
#      - chmod +x ./nodesource_setup.sh
#      - sudo ./nodesource_setup.sh
#      - sudo apt-get -y install nodejs
      - curl -sL https://deb.nodesource.com/setup_6.x | sudo -E bash -
      - sudo apt-get install -y nodejs
#      - sudo ln -s /usr/bin/nodejs /usr/bin/node
      - npm --version
      - node --version
      - docker --version
  pre_build:
    commands:
      - echo -n "$CODEBUILD_BUILD_ID" | sed "s/.*:\([[:xdigit:]]\{7\}\).*/\1/" > /tmp/build_id.out
      - printf "%s:%s" "$REPOSITORY_URI" "$(cat /tmp/build_id.out)" > /tmp/build_tag.out
      - printf '{"tag":"%s"}' "$(cat /tmp/build_id.out)" > /tmp/build.json
      - cat /tmp/build_id.out
      - cat /tmp/build_tag.out
      - cat /tmp/build.json
      - npm update
      - npm install
      - $(aws ecr get-login)
  build:
    commands:
#      - CHROME_BIN=/usr/bin/google-chrome xvfb-run -s '-screen 0 1280x1024x16' npm run test:ci
      - npm run lint
      - npm run build:prod
      - docker build --tag "$(cat /tmp/build_tag.out)" .
  post_build:
    commands:
      - docker push "$(cat /tmp/build_tag.out)"
artifacts:
  files: /tmp/build.json
  discard-paths: yes
