image:
  repository: 006393696278.dkr.ecr.us-east-1.amazonaws.com/twig2
  tag: "latest"
  pullPolicy: Always
service:
  hostName: twig2.riglet
app:
  eolasUrl: http://eolas.riglet/ # ---- Same eolas note
  noauth: true

