image:
  repository: 006393696278.dkr.ecr.us-east-1.amazonaws.com/twig
  tag: "latest"
  pullPolicy: Always
service:
  publicHostName: twig.apps.k8s.riglet.io
app:
  authUrl: http://heimdall.prod.apps.k8s.riglet.io/
  noauth: false
