---
resource_types:
  - name: npm-cache
    type: docker-image
    source: {repository: ymedlop/npm-cache-resource, tag: "latest"}
  - name: slack-notification
    type: docker-image
    source:
      repository: cfcommunity/slack-notification-resource
      tag: latest

resources:
- name: twig
  type: git
  source: &repo-source
    uri: https://github.com/buildit/twig.git
    branch: concourse
- name: dependency-cache
  type: npm-cache
  source:
    <<: *repo-source
    paths:
      - package.json
- name: ng-cli-e2e
  type: docker-image
  source:
    repository: trion/ng-cli-e2e
- name: couchdb
  type: docker-image
  source:
    repository: couchdb
- name: twig-api
  type: docker-image
  source:
    repository: benaychh/twig-api
- name: twig-docker-image
  type: docker-image
  source:
    tag: latest-commit
    email: {{docker-hub-email}}
    username: {{docker-hub-username}}
    password: {{docker-hub-password}}
    repository: {{docker-hub-repo}}


jobs:
- name: Install Dependencies
  plan:
    - get: twig
      trigger: true
- name: Lint Twig Code Base
  plan:
    - get: dependency-cache
      trigger: true
      passed: [Install Dependencies]
    - task: handle dependencies
      file: twtwig-with-depsig/concourse/tasks/dependencies.yml
    - task: lint the project
      file: twig-with-deps/concourse/tasks/lint.yml
- name: Run Unit Tests
  plan:
    - get: dependency-cache
      trigger: true
      passed: [Install Dependencies]
    - task: handle dependencies
      file: twig-with-deps/concourse/tasks/dependencies.yml
    - task: run the unit tests
      file: twig-with-deps/concourse/tasks/run_unit_tests.yml
- name: Build Docker Image
  plan:
    - get: dependency-cache
      trigger: true
      passed: [Lint Twig Code Base, Run Unit Tests]
    - task: handle dependencies
      file: twig-with-deps/concourse/tasks/dependencies.yml
    - task: compile angular project
      file: twig-with-deps/concourse/tasks/compile.yml
    - put: twig-docker-image
      params:
        build: twig-with-dist
- name: Integration Tests
  plan:
    - get: twig
    - get: ng-cli-e2e
      params:
        save: true
    - get: couchdb
      params:
        save: true
    - get: twig-api
      params:
        save: true
    - get: twig-docker-image
      trigger: true
      passed: [Build Docker Image]
      params:
        save: true
    - task: run e2e tests
      privileged: true
      file: twig/concourse/tasks/run_e2e_tests.yml
- name: Deploy to Staging
  plan:
    - get: twig
    - get: twig-docker-image
      trigger: true
      passed: [Integration Tests]
      params:
        save: true
    - put: twig-docker-image
      params:
        load: twig-docker-image
        tag: twig/concourse/vars/docker-staging-tag
