---
resource_types:
  - name: ben-npm-cache
    type: docker-image
    source:
      repository: benaychh/npm-cache
      tag: latest

resources:
  - name: twig
    type: git
    source: &repo-source
      uri: https://github.com/buildit/twig.git
      branch: concourse
  - name: dependency-cache
    type: ben-npm-cache
    source:
      <<: *repo-source
      paths:
        - package.json

jobs:
  - name: Install Dependencies
    plan:
      - get: twig
        trigger: true
      - get: dependency-cache
  - name: Run Tests
    plan:
      - get: twig
        trigger: true
        passed: [Install Dependencies]
      - get: dependency-cache
        passed: [Install Dependencies]
      - task: run the unit tests
        file: twig/concourse/tasks/run_unit_tests.yml
  - name: Build Twig
    plan:
      - get: twig
        trigger: true
        passed: [Run Tests]
      - get: dependency-cache
        passed: [Install Dependencies]
      - task: build the dist
        file: twig/concourse/tasks/build.yml
