---
resource_types:
  - name: npm-cache
    type: docker-image
    source: {repository: ymedlop/npm-cache-resource, tag: "latest"}

resources:
- name: twig
  type: git
  source: &repo-source
    uri: https://github.com/buildit/twig.git
    branch: concourse
- name: dependency-cache
  type: npm-cache
  source:
    <<: *repo-source
    paths:
      - package.json

jobs:
- name: Install Dependencies
  plan:
    - get: twig
      trigger: true
    - get: dependency-cache
- name: Build Twig
  plan:
    - get: twig
      passed: [Install Dependencies]
    - get: dependency-cache
      trigger: true
      passed: [Install Dependencies]
    - task: build the dist
      file: twig/concourse/tasks/build.yml
- name: Run Tests
  plan:
    - get: twig
      passed: [Install Dependencies]
    - get: dependency-cache
      trigger: true
      passed: [Install Dependencies]
    - task: run the unit tests
      file: twig/concourse/tasks/run_unit_tests.yml
- name: Deploy
  plan:
    - get: twig
      trigger: true
      passed: [Run Tests, Build Twig]
    - task: deploy the new whatever
      file: twig/conconcorse/tasks/deploy.yml

