---
resource_types:
  - name: npm-cache
    type: docker-image
    source: {repository: ymedlop/npm-cache-resource, tag: "latest"}
  - name: slack-notification
    type: docker-image
    source:
      repository: cfcommunity/slack-notification-resource
      tag: latest

resources:
- name: twig
  type: git
  source: &repo-source
    uri: https://github.com/buildit/twig.git
    branch: concourse
- name: dependency-cache
  type: npm-cache
  source:
    <<: *repo-source
    paths:
      - package.json
- name: twig-docker-image
  type: docker-image
  source:
    email: {{docker-hub-email}}
    username: {{docker-hub-username}}
    password: {{docker-hub-password}}
    repository: {{docker-hub-repo}}

jobs:
- name: Install Dependencies
  plan:
    - get: twig
      trigger: true
    - get: dependency-cache
# - name: Lint Twig Code Base
#   plan:
#     - get: twig
#       trigger: true
#       passed: [Install Dependencies]
#     - get: dependency-cache
#       passed: [Install Dependencies]
#     - task: handle dependencies
#       file: twig/concourse/tasks/dependencies.yml
#     - task: lint the project
#       file: twig/concourse/tasks/lint.yml
# - name: Run Unit Tests
#   plan:
#     - get: twig
#       trigger: true
#       passed: [Install Dependencies]
#     - get: dependency-cache
#       passed: [Install Dependencies]
#     - task: handle dependencies
#       file: twig/concourse/tasks/dependencies.yml
#     - task: run the unit tests
#       file: twig/concourse/tasks/run_unit_tests.yml
- name: Deploy
  plan:
    - get: twig
      trigger: true
      passed: [Install Dependencies]
    - get: dependency-cache
      passed: [Install Dependencies]
    - task: handle dependencies
      file: twig/concourse/tasks/dependencies.yml
    - task: compile angular project
      file: twig/concourse/tasks/compile.yml
    - put: twig-docker-image
      params:
        build: twig-with-dist

# - name: Notify Slack
#   plan:
#   - get: twig
#     trigger: true
#     passed: [Deploy]
#   - put: slack-alert
#     params:
#       channel: '#twig'
#       text: Built via Concourse to https://hub.docker.com/r/benaychh/twig/

- name: Integration Tests
  plan:
    - get: twig
      trigger: true
      passed: [Deploy]
    - get: dependency-cache
      passed: [Install Dependencies]
    - task: run e2e tests
      privileged: true
      file: twig/concourse/tasks/run_e2e_tests.yml
