---
resource_types:
  - name: npm-cache
    type: docker-image
    source: {repository: ymedlop/npm-cache-resource, tag: "latest"}

resources:
- name: twig
  type: git
  source: &repo-source
    uri: https://github.com/buildit/twig.git
    branch: concourse
# - name: dependency-cache
#   type: npm-cache
#   source:
#     <<: *repo-source
#     paths:
#       - package.json

jobs:
# - name: Install Dependencies
#   plan:
#     - get: twig
#       trigger: true
#     - get: dependency-cache

# - name: Run Tests
#   plan:
#     - get: twig
#       trigger: true
#       passed: [Install Dependencies]
#     - get: dependency-cache
#       passed: [Install Dependencies]
#     - task: handle dependencies
#       file: twig/concourse/tasks/dependencies.yml
#     - task: lint the project
#       file: twig/concourse/tasks/lint.yml
#     - task: run the unit tests
#       file: twig/concourse/tasks/run_unit_tests.yml

- name: Deploy
  plan:
    - get: twig
      trigger: true
      # passed: [Install Dependencies]
    # - get: dependency-cache
    #   passed: [Install Dependencies]
    # - task: handle dependencies
    #   file: twig/concourse/tasks/dependencies.yml
    # - task: compile angular project
    #   file: twig/concourse/tasks/compile.yml
    - task: create and deploy docker container
      params:
        params:
          DOCKER_USERNAME: {{docker-username}}
          DOCKER_PASSWORD: {{docker-password}}
      file: twig/concourse/tasks/deploy_docker.yml

