platform: linux

image_resource:
  type: docker-image
  source:
    repository: benaychh/random
    tag: latest

inputs:
  - name: twig-with-dependencies

outputs:
  - name: built-twig

run:
  path: twig/concourse/scripts/build.sh
