platform: linux

image_resource:
  type: docker-image
  source:
    repository: markhobson/node-chrome
    tag: latest

inputs:
  - name: twig
  - name: dependency-cache

run:
  path: twig/concourse/scripts/run_unit_tests.sh
