platform: linux

image_resource:
  type: docker-image
  source:
    repository: docker/compose
    tag: latest

inputs:
  - name: twig-with-deps

run:
  path: ./twig-with-deps/concourse/scripts/run_e2e_tests.sh
